import {useState} from 'react';
import {Link} from '@tanstack/react-router';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {toast} from 'sonner';
import {supabase} from '@/lib/nex/supabase';
import {Boton,claseCampo} from './campos';
export function PendientesProyectian(){
 const [instalaciones,setInstalaciones]=useState<Record<string,string>>({});const [creada,setCreada]=useState<string|null>(null);const qc=useQueryClient();
 const q=useQuery({queryKey:['proyectian_pendientes'],queryFn:async()=>{const {data,error}=await supabase.from('proyectian_objetos').select('*').in('entidad',['pendientes','instalaciones','proyecto_lineas']).limit(1000);if(error)throw error;return data;}});
 const crear=useMutation({mutationFn:async(v:{enlace:string;id:string})=>{const {data,error}=await supabase.rpc('crear_orden_desde_proyectian',{p_enlace:v.enlace,p_pendiente:v.id,...(instalaciones[v.id]?{p_instalacion:instalaciones[v.id]}:{})});if(error)throw error;return data;},onSuccess:id=>{setCreada(id);void qc.invalidateQueries({queryKey:['ordenes']});toast.success('Orden preparada. Repetir devuelve la misma orden.');},onError:e=>toast.error(e.message)});
 const pendientes=q.data?.filter(x=>x.entidad==='pendientes'&&['pendiente','haciendo'].includes(String((x.datos as Record<string,unknown>)['estado'])));
 return <details className="border-t pt-3"><summary className="cursor-pointer font-medium">Crear trabajo desde un pendiente del producto</summary><p className="my-2 text-sm text-muted-foreground">Conserva el origen, la línea y el contexto de la última copia confirmada. Se prepara una única orden pendiente de aprobación; no empieza a consumir IA.</p>{q.error?<p role="alert">No se pudieron consultar los pendientes.</p>:q.isPending?<p role="status">Consultando pendientes…</p>:!pendientes?.length?<p className="text-sm">No hay pendientes sincronizados disponibles.</p>:pendientes.map(x=>{const d=x.datos as Record<string,unknown>;return <div key={`${x.enlace_id}/${x.id}`} className="my-3 space-y-2 rounded border p-3"><p>{String(d['titulo']??'Pendiente')}</p><p className="text-xs">Línea de origen: {d['linea_id']?String((q.data?.find(l=>l.entidad==='proyecto_lineas'&&l.enlace_id===x.enlace_id&&l.id===d['linea_id'])?.datos as Record<string,unknown>|undefined)?.['nombre']??'Línea pendiente de comprobar'):'General del producto'}</p><select className={claseCampo} aria-label={`Instalación para ${String(d['titulo'])}`} value={instalaciones[x.id]??''} onChange={e=>setInstalaciones({...instalaciones,[x.id]:e.target.value})}><option value="">Sin instalación concreta</option>{q.data?.filter(i=>i.entidad==='instalaciones'&&i.enlace_id===x.enlace_id&&(!d['linea_id']||(i.datos as Record<string,unknown>)['linea_id']===d['linea_id'])).map(i=><option key={i.id} value={i.id}>{String((i.datos as Record<string,unknown>)['nombre']??i.id)}</option>)}</select><Boton variante="suave" disabled={crear.isPending} onClick={()=>crear.mutate({enlace:x.enlace_id,id:x.id})}>{crear.isPending?'Preparando…':'Preparar orden'}</Boton></div>})}{creada?<Link to="/aprobaciones" className="text-primary underline">Abrir orden preparada</Link>:null}</details>;
}
