import type {
  Agente,
  Alerta,
  EventoActividad,
  Integracion,
  Mensaje,
  Preview,
  Proyecto,
  Tarea,
} from "./types";

const ahora = Date.now();
const dias = (n: number) => new Date(ahora - n * 86400000).toISOString();
const horas = (n: number) => new Date(ahora - n * 3600000).toISOString();

export const AGENTES: Agente[] = [
  {
    id: "claude",
    nombre: "Claude",
    proveedor: "Anthropic",
    especialidades: ["Arquitectura", "Código complejo", "Revisión"],
    costeRelativo: 4,
    calidad: 94,
    rapidez: 78,
    disponibilidad: "sin_configurar",
    tareasActivas: 3,
    capacidad: 6,
    permisos: ["Leer repositorio", "Proponer cambios"],
    conectado: false,
  },
  {
    id: "chatgpt",
    nombre: "ChatGPT",
    proveedor: "OpenAI",
    especialidades: ["Planificación", "Redacción", "Análisis"],
    costeRelativo: 3,
    calidad: 90,
    rapidez: 86,
    disponibilidad: "sin_configurar",
    tareasActivas: 2,
    capacidad: 6,
    permisos: ["Leer contexto de proyecto"],
    conectado: false,
  },
  {
    id: "gemini",
    nombre: "Gemini",
    proveedor: "Google",
    especialidades: ["Documentos largos", "Datos", "Multimodal"],
    costeRelativo: 2,
    calidad: 86,
    rapidez: 90,
    disponibilidad: "sin_configurar",
    tareasActivas: 1,
    capacidad: 5,
    permisos: ["Leer contexto de proyecto"],
    conectado: false,
  },
  {
    id: "lovable",
    nombre: "Lovable",
    proveedor: "Lovable",
    especialidades: ["Interfaces web", "Prototipos rápidos"],
    costeRelativo: 3,
    calidad: 84,
    rapidez: 92,
    disponibilidad: "sin_configurar",
    tareasActivas: 2,
    capacidad: 4,
    permisos: ["Crear páginas", "Publicar vista previa"],
    conectado: false,
  },
  {
    id: "canva",
    nombre: "Canva",
    proveedor: "Canva",
    especialidades: ["Diseño gráfico", "Plantillas", "Marca"],
    costeRelativo: 1,
    calidad: 76,
    rapidez: 88,
    disponibilidad: "sin_configurar",
    tareasActivas: 0,
    capacidad: 3,
    permisos: ["Generar piezas gráficas"],
    conectado: false,
  },
  {
    id: "nano-banana",
    nombre: "Nano Banana",
    proveedor: "Google",
    especialidades: ["Imágenes", "Retoque", "Variaciones"],
    costeRelativo: 2,
    calidad: 82,
    rapidez: 94,
    disponibilidad: "sin_configurar",
    tareasActivas: 1,
    capacidad: 4,
    permisos: ["Generar imágenes"],
    conectado: false,
  },
];

export const PROYECTOS: Proyecto[] = [
  {
    id: "nexdeveloper",
    nombre: "NexDeveloper",
    descripcion: "Centro de control multiagente para todos los proyectos.",
    estado: "ejecutando",
    prioridad: "critica",
    presupuesto: 1800,
    consumido: 612,
    repositorio: "nexdeveloper",
    agentes: ["claude", "lovable"],
    alertas: ["Falta enlazar la base de datos propia"],
    actualizadoEl: horas(1),
  },
  {
    id: "atlas-crm",
    nombre: "Atlas CRM",
    descripcion: "CRM interno con automatizaciones de seguimiento comercial.",
    estado: "esperando_revision",
    prioridad: "alta",
    presupuesto: 2400,
    consumido: 1890,
    repositorio: "atlas-crm",
    agentes: ["claude", "chatgpt"],
    alertas: ["Revisión pendiente del módulo de facturación"],
    actualizadoEl: horas(5),
  },
  {
    id: "portal-clientes",
    nombre: "Portal de Clientes",
    descripcion: "Área privada con documentos, avisos y firma digital.",
    estado: "en_cola",
    prioridad: "media",
    presupuesto: 1500,
    consumido: 340,
    agentes: ["lovable"],
    alertas: [],
    actualizadoEl: dias(1),
  },
  {
    id: "marca-visual",
    nombre: "Identidad Visual",
    descripcion: "Sistema de marca, plantillas y piezas para redes.",
    estado: "planificando",
    prioridad: "baja",
    presupuesto: 700,
    consumido: 95,
    agentes: ["canva", "nano-banana"],
    alertas: [],
    actualizadoEl: dias(2),
  },
  {
    id: "motor-informes",
    nombre: "Motor de Informes",
    descripcion: "Generación automática de informes en PDF por cliente.",
    estado: "bloqueado",
    prioridad: "alta",
    presupuesto: 1300,
    consumido: 880,
    repositorio: "motor-informes",
    agentes: ["gemini"],
    alertas: ["Bloqueado: faltan credenciales del servidor de correo"],
    actualizadoEl: dias(3),
  },
  {
    id: "tienda-online",
    nombre: "Tienda Online",
    descripcion: "Catálogo, carrito y pasarela de pago.",
    estado: "pendiente",
    prioridad: "media",
    presupuesto: 2000,
    consumido: 0,
    agentes: [],
    alertas: ["Sin agente asignado"],
    actualizadoEl: dias(4),
  },
  {
    id: "asistente-soporte",
    nombre: "Asistente de Soporte",
    descripcion: "Agente de respuesta con base de conocimiento propia.",
    estado: "ejecutando",
    prioridad: "alta",
    presupuesto: 1600,
    consumido: 1105,
    agentes: ["chatgpt", "gemini"],
    alertas: [],
    actualizadoEl: horas(3),
  },
  {
    id: "web-corporativa",
    nombre: "Web Corporativa",
    descripcion: "Sitio público con blog y captación de contactos.",
    estado: "completado",
    prioridad: "baja",
    presupuesto: 900,
    consumido: 845,
    repositorio: "web-corporativa",
    agentes: ["lovable", "canva"],
    alertas: [],
    actualizadoEl: dias(9),
  },
];

export const TAREAS: Tarea[] = [
  t("nexdeveloper", "Esquema de base de datos y políticas", "ejecutando", "claude", "critica", 0.5, 8, 3.5, 120, 52, 45),
  t("nexdeveloper", "Panel de inicio y filtros", "completada", "lovable", "alta", 2, 6, 6, 80, 78, 100),
  t("nexdeveloper", "Plan de trabajo por proyecto", "completada", "lovable", "alta", 1.5, 5, 5, 70, 66, 100),
  t("nexdeveloper", "Adaptadores de agentes", "en_cola", "claude", "alta", 0.2, 10, 0, 160, 0, 0),
  t("nexdeveloper", "Vault de secretos cifrado", "pendiente", null, "critica", 0.1, 12, 0, 190, 0, 0),
  t("atlas-crm", "Módulo de facturación", "esperando_revision", "claude", "alta", 3, 14, 13, 240, 228, 92),
  t("atlas-crm", "Importar contactos antiguos", "completada", "chatgpt", "media", 6, 5, 5, 60, 58, 100),
  t("atlas-crm", "Panel de previsiones", "ejecutando", "chatgpt", "media", 1, 9, 4, 110, 48, 40),
  t("portal-clientes", "Firma digital de documentos", "en_cola", "lovable", "alta", 1, 11, 0, 150, 0, 0),
  t("portal-clientes", "Área de descargas", "pendiente", null, "baja", 2, 4, 0, 50, 0, 0),
  t("marca-visual", "Manual de marca", "ejecutando", "canva", "baja", 2, 6, 2, 45, 15, 30),
  t("marca-visual", "Set de imágenes para redes", "pendiente", "nano-banana", "baja", 2, 3, 0, 25, 0, 0),
  t("motor-informes", "Envío programado de informes", "bloqueada", "gemini", "alta", 5, 7, 3, 90, 40, 35),
  t("motor-informes", "Plantillas PDF", "completada", "gemini", "media", 8, 6, 6, 70, 68, 100),
  t("tienda-online", "Definir catálogo y categorías", "pendiente", null, "media", 4, 5, 0, 60, 0, 0),
  t("asistente-soporte", "Base de conocimiento", "ejecutando", "gemini", "alta", 1, 10, 6, 130, 76, 60),
  t("asistente-soporte", "Respuestas con citas", "esperando_revision", "chatgpt", "alta", 2, 8, 8, 120, 118, 95),
  t("web-corporativa", "Blog y SEO", "completada", "lovable", "baja", 12, 9, 9, 95, 92, 100),
];

function t(
  proyectoId: string,
  titulo: string,
  estado: Tarea["estado"],
  agenteId: string | null,
  prioridad: Tarea["prioridad"],
  diasDesdeEnvio: number,
  estimacionHoras: number,
  horasConsumidas: number,
  costeEstimado: number,
  costeConsumido: number,
  progreso: number,
): Tarea {
  return {
    id: `${proyectoId}-${titulo.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 28)}`,
    proyectoId,
    titulo,
    estado,
    agenteId,
    prioridad,
    enviadaEl: dias(diasDesdeEnvio),
    estimacionHoras,
    horasConsumidas,
    costeEstimado,
    costeConsumido,
    progreso,
    completadaPor: estado === "completada" ? "Javier Romero" : undefined,
    completadaEl: estado === "completada" ? dias(Math.max(0, diasDesdeEnvio - 1)) : undefined,
    ultimaActividad: horas(Math.round(diasDesdeEnvio * 6) + 1),
  };
}

export const MENSAJES: Mensaje[] = [
  {
    id: "m1",
    proyectoId: "nexdeveloper",
    autor: "usuario",
    texto: "Prepara el esquema de datos y las políticas de acceso por usuario.",
    fecha: horas(9),
  },
  {
    id: "m2",
    proyectoId: "nexdeveloper",
    autor: "agente",
    agenteId: "claude",
    texto:
      "Propuesta: doce tablas con acceso restringido por propietario. Necesito autorización para tocar credenciales.",
    fecha: horas(8),
  },
  {
    id: "m3",
    proyectoId: "atlas-crm",
    autor: "usuario",
    texto: "El módulo de facturación necesita revisión antes de publicarlo.",
    fecha: horas(6),
  },
  {
    id: "m4",
    proyectoId: "asistente-soporte",
    autor: "agente",
    agenteId: "gemini",
    texto: "Base de conocimiento indexada al 60%. Sin incidencias.",
    fecha: horas(2),
  },
];

export const ACTIVIDAD: EventoActividad[] = [
  { id: "a1", proyectoId: "nexdeveloper", tipo: "orden", texto: "Orden enviada: esquema de datos", fecha: horas(9) },
  { id: "a2", proyectoId: "nexdeveloper", tipo: "decision", texto: "Aprobado modo equilibrado", fecha: horas(8) },
  { id: "a3", proyectoId: "nexdeveloper", tipo: "cambio", texto: "Panel de inicio marcado como completado", fecha: horas(4) },
  { id: "a4", proyectoId: "atlas-crm", tipo: "resultado", texto: "Módulo de facturación listo para revisión", fecha: horas(6) },
  {
    id: "a5",
    proyectoId: "atlas-crm",
    tipo: "reorganizacion",
    texto: "Orden movida desde «Portal de Clientes» por coincidencia clara de contenido",
    fecha: dias(1),
  },
  { id: "a6", proyectoId: "motor-informes", tipo: "actividad", texto: "Tarea bloqueada: faltan credenciales", fecha: dias(3) },
];

export const PREVIEWS: Preview[] = [
  { id: "p1", proyectoId: "nexdeveloper", titulo: "Vista previa interna", url: "#", entorno: "desarrollo" },
  { id: "p2", proyectoId: "atlas-crm", titulo: "Entorno de pruebas", url: "#", entorno: "pruebas" },
  { id: "p3", proyectoId: "web-corporativa", titulo: "Sitio publicado", url: "#", entorno: "produccion" },
];

export const INTEGRACIONES: Integracion[] = [
  {
    id: "supabase",
    nombre: "Base de datos propia (Supabase)",
    tipo: "datos",
    conectada: false,
    proyectos: ["nexdeveloper"],
    secretos: [
      { referencia: "SUPABASE_URL", configurado: false },
      { referencia: "SUPABASE_SERVICE_ROLE_KEY", configurado: false },
    ],
    requiereAprobacion: true,
  },
  {
    id: "github",
    nombre: "GitHub",
    tipo: "codigo",
    conectada: false,
    proyectos: ["nexdeveloper", "atlas-crm", "motor-informes", "web-corporativa"],
    secretos: [{ referencia: "GITHUB_TOKEN", configurado: false }],
    requiereAprobacion: true,
  },
  {
    id: "anthropic",
    nombre: "Claude",
    tipo: "modelo",
    conectada: false,
    proyectos: ["nexdeveloper", "atlas-crm"],
    secretos: [{ referencia: "ANTHROPIC_API_KEY", configurado: false }],
    requiereAprobacion: true,
  },
  {
    id: "openai",
    nombre: "ChatGPT",
    tipo: "modelo",
    conectada: false,
    proyectos: ["atlas-crm", "asistente-soporte"],
    secretos: [{ referencia: "OPENAI_API_KEY", configurado: false }],
    requiereAprobacion: true,
  },
  {
    id: "google",
    nombre: "Gemini y Nano Banana",
    tipo: "modelo",
    conectada: false,
    proyectos: ["motor-informes", "asistente-soporte", "marca-visual"],
    secretos: [{ referencia: "GOOGLE_API_KEY", configurado: false }],
    requiereAprobacion: true,
  },
  {
    id: "canva",
    nombre: "Canva",
    tipo: "diseno",
    conectada: false,
    proyectos: ["marca-visual", "web-corporativa"],
    secretos: [{ referencia: "CANVA_API_KEY", configurado: false }],
    requiereAprobacion: false,
  },
];

export const ALERTAS: Alerta[] = [
  {
    id: "al1",
    proyectoId: "nexdeveloper",
    texto: "Falta enlazar tu base de datos propia. Ahora se muestran datos de demostración.",
    nivel: "critico",
    requiereDecision: true,
  },
  {
    id: "al2",
    proyectoId: "atlas-crm",
    texto: "Revisión pendiente del módulo de facturación antes de publicar.",
    nivel: "aviso",
    requiereDecision: true,
  },
  {
    id: "al3",
    proyectoId: "motor-informes",
    texto: "Tarea bloqueada por credenciales del servidor de correo.",
    nivel: "critico",
    requiereDecision: true,
  },
  {
    id: "al4",
    proyectoId: null,
    texto: "Una orden sin proyecto claro espera confirmación en «Sin clasificar».",
    nivel: "info",
    requiereDecision: true,
  },
];
