/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentesRouteImport } from './routes/agentes'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as AprobacionesRouteImport } from './routes/aprobaciones'
import { Route as BandejaRouteImport } from './routes/bandeja'
import { Route as CalidadRouteImport } from './routes/calidad'
import { Route as ColaRouteImport } from './routes/cola'
import { Route as CompilacionesRouteImport } from './routes/compilaciones'
import { Route as CopiasRouteImport } from './routes/copias'
import { Route as DocumentacionRouteImport } from './routes/documentacion'
import { Route as DominiosRouteImport } from './routes/dominios'
import { Route as EstadoRouteImport } from './routes/estado'
import { Route as ExpertosRouteImport } from './routes/expertos'
import { Route as GastoIaRouteImport } from './routes/gasto-ia'
import { Route as HabilidadesRouteImport } from './routes/habilidades'
import { Route as IntegracionesRouteImport } from './routes/integraciones'
import { Route as MesaRouteImport } from './routes/mesa'
import { Route as NuevaOrdenRouteImport } from './routes/nueva-orden'
import { Route as ReferenciaRouteImport } from './routes/referencia'
import { Route as RepositoriosRouteImport } from './routes/repositorios'
import { Route as ResumenesRouteImport } from './routes/resumenes'
import { Route as VigilanciaRouteImport } from './routes/vigilancia'
import { Route as VozRouteImport } from './routes/voz'
import { Route as AjustesProveedoresRouteImport } from './routes/ajustes_.proveedores'
import { Route as ProyectosIndexRouteImport } from './routes/proyectos/index'
import { Route as ProyectosProyectoIdRouteImport } from './routes/proyectos/$proyectoId'
import { Route as AjustesProveedoresCanvaRetornoRouteImport } from './routes/ajustes_.proveedores.canva.retorno'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentesRoute = AgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const AprobacionesRoute = AprobacionesRouteImport.update({
  id: '/aprobaciones',
  path: '/aprobaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const BandejaRoute = BandejaRouteImport.update({
  id: '/bandeja',
  path: '/bandeja',
  getParentRoute: () => rootRouteImport,
} as any)
const CalidadRoute = CalidadRouteImport.update({
  id: '/calidad',
  path: '/calidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaRoute = ColaRouteImport.update({
  id: '/cola',
  path: '/cola',
  getParentRoute: () => rootRouteImport,
} as any)
const CompilacionesRoute = CompilacionesRouteImport.update({
  id: '/compilaciones',
  path: '/compilaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const CopiasRoute = CopiasRouteImport.update({
  id: '/copias',
  path: '/copias',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentacionRoute = DocumentacionRouteImport.update({
  id: '/documentacion',
  path: '/documentacion',
  getParentRoute: () => rootRouteImport,
} as any)
const DominiosRoute = DominiosRouteImport.update({
  id: '/dominios',
  path: '/dominios',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadoRoute = EstadoRouteImport.update({
  id: '/estado',
  path: '/estado',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertosRoute = ExpertosRouteImport.update({
  id: '/expertos',
  path: '/expertos',
  getParentRoute: () => rootRouteImport,
} as any)
const GastoIaRoute = GastoIaRouteImport.update({
  id: '/gasto-ia',
  path: '/gasto-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const HabilidadesRoute = HabilidadesRouteImport.update({
  id: '/habilidades',
  path: '/habilidades',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracionesRoute = IntegracionesRouteImport.update({
  id: '/integraciones',
  path: '/integraciones',
  getParentRoute: () => rootRouteImport,
} as any)
const MesaRoute = MesaRouteImport.update({
  id: '/mesa',
  path: '/mesa',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaOrdenRoute = NuevaOrdenRouteImport.update({
  id: '/nueva-orden',
  path: '/nueva-orden',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenciaRoute = ReferenciaRouteImport.update({
  id: '/referencia',
  path: '/referencia',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriosRoute = RepositoriosRouteImport.update({
  id: '/repositorios',
  path: '/repositorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumenesRoute = ResumenesRouteImport.update({
  id: '/resumenes',
  path: '/resumenes',
  getParentRoute: () => rootRouteImport,
} as any)
const VigilanciaRoute = VigilanciaRouteImport.update({
  id: '/vigilancia',
  path: '/vigilancia',
  getParentRoute: () => rootRouteImport,
} as any)
const VozRoute = VozRouteImport.update({
  id: '/voz',
  path: '/voz',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesProveedoresRoute = AjustesProveedoresRouteImport.update({
  id: '/ajustes_/proveedores',
  path: '/ajustes/proveedores',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosIndexRoute = ProyectosIndexRouteImport.update({
  id: '/proyectos/',
  path: '/proyectos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosProyectoIdRoute = ProyectosProyectoIdRouteImport.update({
  id: '/proyectos/$proyectoId',
  path: '/proyectos/$proyectoId',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesProveedoresCanvaRetornoRoute =
  AjustesProveedoresCanvaRetornoRouteImport.update({
    id: '/canva/retorno',
    path: '/canva/retorno',
    getParentRoute: () => AjustesProveedoresRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/ajustes': typeof AjustesRoute
  '/aprobaciones': typeof AprobacionesRoute
  '/bandeja': typeof BandejaRoute
  '/calidad': typeof CalidadRoute
  '/cola': typeof ColaRoute
  '/compilaciones': typeof CompilacionesRoute
  '/copias': typeof CopiasRoute
  '/documentacion': typeof DocumentacionRoute
  '/dominios': typeof DominiosRoute
  '/estado': typeof EstadoRoute
  '/expertos': typeof ExpertosRoute
  '/gasto-ia': typeof GastoIaRoute
  '/habilidades': typeof HabilidadesRoute
  '/integraciones': typeof IntegracionesRoute
  '/mesa': typeof MesaRoute
  '/nueva-orden': typeof NuevaOrdenRoute
  '/referencia': typeof ReferenciaRoute
  '/repositorios': typeof RepositoriosRoute
  '/resumenes': typeof ResumenesRoute
  '/vigilancia': typeof VigilanciaRoute
  '/voz': typeof VozRoute
  '/ajustes/proveedores': typeof AjustesProveedoresRouteWithChildren
  '/proyectos/$proyectoId': typeof ProyectosProyectoIdRoute
  '/proyectos/': typeof ProyectosIndexRoute
  '/ajustes/proveedores/canva/retorno': typeof AjustesProveedoresCanvaRetornoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/ajustes': typeof AjustesRoute
  '/aprobaciones': typeof AprobacionesRoute
  '/bandeja': typeof BandejaRoute
  '/calidad': typeof CalidadRoute
  '/cola': typeof ColaRoute
  '/compilaciones': typeof CompilacionesRoute
  '/copias': typeof CopiasRoute
  '/documentacion': typeof DocumentacionRoute
  '/dominios': typeof DominiosRoute
  '/estado': typeof EstadoRoute
  '/expertos': typeof ExpertosRoute
  '/gasto-ia': typeof GastoIaRoute
  '/habilidades': typeof HabilidadesRoute
  '/integraciones': typeof IntegracionesRoute
  '/mesa': typeof MesaRoute
  '/nueva-orden': typeof NuevaOrdenRoute
  '/referencia': typeof ReferenciaRoute
  '/repositorios': typeof RepositoriosRoute
  '/resumenes': typeof ResumenesRoute
  '/vigilancia': typeof VigilanciaRoute
  '/voz': typeof VozRoute
  '/ajustes/proveedores': typeof AjustesProveedoresRouteWithChildren
  '/proyectos/$proyectoId': typeof ProyectosProyectoIdRoute
  '/proyectos': typeof ProyectosIndexRoute
  '/ajustes/proveedores/canva/retorno': typeof AjustesProveedoresCanvaRetornoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/ajustes': typeof AjustesRoute
  '/aprobaciones': typeof AprobacionesRoute
  '/bandeja': typeof BandejaRoute
  '/calidad': typeof CalidadRoute
  '/cola': typeof ColaRoute
  '/compilaciones': typeof CompilacionesRoute
  '/copias': typeof CopiasRoute
  '/documentacion': typeof DocumentacionRoute
  '/dominios': typeof DominiosRoute
  '/estado': typeof EstadoRoute
  '/expertos': typeof ExpertosRoute
  '/gasto-ia': typeof GastoIaRoute
  '/habilidades': typeof HabilidadesRoute
  '/integraciones': typeof IntegracionesRoute
  '/mesa': typeof MesaRoute
  '/nueva-orden': typeof NuevaOrdenRoute
  '/referencia': typeof ReferenciaRoute
  '/repositorios': typeof RepositoriosRoute
  '/resumenes': typeof ResumenesRoute
  '/vigilancia': typeof VigilanciaRoute
  '/voz': typeof VozRoute
  '/ajustes_/proveedores': typeof AjustesProveedoresRouteWithChildren
  '/proyectos/$proyectoId': typeof ProyectosProyectoIdRoute
  '/proyectos/': typeof ProyectosIndexRoute
  '/ajustes_/proveedores/canva/retorno': typeof AjustesProveedoresCanvaRetornoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agentes'
    | '/ajustes'
    | '/aprobaciones'
    | '/bandeja'
    | '/calidad'
    | '/cola'
    | '/compilaciones'
    | '/copias'
    | '/documentacion'
    | '/dominios'
    | '/estado'
    | '/expertos'
    | '/gasto-ia'
    | '/habilidades'
    | '/integraciones'
    | '/mesa'
    | '/nueva-orden'
    | '/referencia'
    | '/repositorios'
    | '/resumenes'
    | '/vigilancia'
    | '/voz'
    | '/ajustes/proveedores'
    | '/proyectos/$proyectoId'
    | '/proyectos/'
    | '/ajustes/proveedores/canva/retorno'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agentes'
    | '/ajustes'
    | '/aprobaciones'
    | '/bandeja'
    | '/calidad'
    | '/cola'
    | '/compilaciones'
    | '/copias'
    | '/documentacion'
    | '/dominios'
    | '/estado'
    | '/expertos'
    | '/gasto-ia'
    | '/habilidades'
    | '/integraciones'
    | '/mesa'
    | '/nueva-orden'
    | '/referencia'
    | '/repositorios'
    | '/resumenes'
    | '/vigilancia'
    | '/voz'
    | '/ajustes/proveedores'
    | '/proyectos/$proyectoId'
    | '/proyectos'
    | '/ajustes/proveedores/canva/retorno'
  id:
    | '__root__'
    | '/'
    | '/agentes'
    | '/ajustes'
    | '/aprobaciones'
    | '/bandeja'
    | '/calidad'
    | '/cola'
    | '/compilaciones'
    | '/copias'
    | '/documentacion'
    | '/dominios'
    | '/estado'
    | '/expertos'
    | '/gasto-ia'
    | '/habilidades'
    | '/integraciones'
    | '/mesa'
    | '/nueva-orden'
    | '/referencia'
    | '/repositorios'
    | '/resumenes'
    | '/vigilancia'
    | '/voz'
    | '/ajustes_/proveedores'
    | '/proyectos/$proyectoId'
    | '/proyectos/'
    | '/ajustes_/proveedores/canva/retorno'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentesRoute: typeof AgentesRoute
  AjustesRoute: typeof AjustesRoute
  AprobacionesRoute: typeof AprobacionesRoute
  BandejaRoute: typeof BandejaRoute
  CalidadRoute: typeof CalidadRoute
  ColaRoute: typeof ColaRoute
  CompilacionesRoute: typeof CompilacionesRoute
  CopiasRoute: typeof CopiasRoute
  DocumentacionRoute: typeof DocumentacionRoute
  DominiosRoute: typeof DominiosRoute
  EstadoRoute: typeof EstadoRoute
  ExpertosRoute: typeof ExpertosRoute
  GastoIaRoute: typeof GastoIaRoute
  HabilidadesRoute: typeof HabilidadesRoute
  IntegracionesRoute: typeof IntegracionesRoute
  MesaRoute: typeof MesaRoute
  NuevaOrdenRoute: typeof NuevaOrdenRoute
  ReferenciaRoute: typeof ReferenciaRoute
  RepositoriosRoute: typeof RepositoriosRoute
  ResumenesRoute: typeof ResumenesRoute
  VigilanciaRoute: typeof VigilanciaRoute
  VozRoute: typeof VozRoute
  AjustesProveedoresRoute: typeof AjustesProveedoresRouteWithChildren
  ProyectosProyectoIdRoute: typeof ProyectosProyectoIdRoute
  ProyectosIndexRoute: typeof ProyectosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentes': {
      id: '/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AgentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprobaciones': {
      id: '/aprobaciones'
      path: '/aprobaciones'
      fullPath: '/aprobaciones'
      preLoaderRoute: typeof AprobacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bandeja': {
      id: '/bandeja'
      path: '/bandeja'
      fullPath: '/bandeja'
      preLoaderRoute: typeof BandejaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calidad': {
      id: '/calidad'
      path: '/calidad'
      fullPath: '/calidad'
      preLoaderRoute: typeof CalidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cola': {
      id: '/cola'
      path: '/cola'
      fullPath: '/cola'
      preLoaderRoute: typeof ColaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compilaciones': {
      id: '/compilaciones'
      path: '/compilaciones'
      fullPath: '/compilaciones'
      preLoaderRoute: typeof CompilacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copias': {
      id: '/copias'
      path: '/copias'
      fullPath: '/copias'
      preLoaderRoute: typeof CopiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentacion': {
      id: '/documentacion'
      path: '/documentacion'
      fullPath: '/documentacion'
      preLoaderRoute: typeof DocumentacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dominios': {
      id: '/dominios'
      path: '/dominios'
      fullPath: '/dominios'
      preLoaderRoute: typeof DominiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estado': {
      id: '/estado'
      path: '/estado'
      fullPath: '/estado'
      preLoaderRoute: typeof EstadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertos': {
      id: '/expertos'
      path: '/expertos'
      fullPath: '/expertos'
      preLoaderRoute: typeof ExpertosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gasto-ia': {
      id: '/gasto-ia'
      path: '/gasto-ia'
      fullPath: '/gasto-ia'
      preLoaderRoute: typeof GastoIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habilidades': {
      id: '/habilidades'
      path: '/habilidades'
      fullPath: '/habilidades'
      preLoaderRoute: typeof HabilidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integraciones': {
      id: '/integraciones'
      path: '/integraciones'
      fullPath: '/integraciones'
      preLoaderRoute: typeof IntegracionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesa': {
      id: '/mesa'
      path: '/mesa'
      fullPath: '/mesa'
      preLoaderRoute: typeof MesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-orden': {
      id: '/nueva-orden'
      path: '/nueva-orden'
      fullPath: '/nueva-orden'
      preLoaderRoute: typeof NuevaOrdenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referencia': {
      id: '/referencia'
      path: '/referencia'
      fullPath: '/referencia'
      preLoaderRoute: typeof ReferenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositorios': {
      id: '/repositorios'
      path: '/repositorios'
      fullPath: '/repositorios'
      preLoaderRoute: typeof RepositoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumenes': {
      id: '/resumenes'
      path: '/resumenes'
      fullPath: '/resumenes'
      preLoaderRoute: typeof ResumenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vigilancia': {
      id: '/vigilancia'
      path: '/vigilancia'
      fullPath: '/vigilancia'
      preLoaderRoute: typeof VigilanciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voz': {
      id: '/voz'
      path: '/voz'
      fullPath: '/voz'
      preLoaderRoute: typeof VozRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes_/proveedores': {
      id: '/ajustes_/proveedores'
      path: '/ajustes/proveedores'
      fullPath: '/ajustes/proveedores'
      preLoaderRoute: typeof AjustesProveedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/': {
      id: '/proyectos/'
      path: '/proyectos'
      fullPath: '/proyectos/'
      preLoaderRoute: typeof ProyectosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/$proyectoId': {
      id: '/proyectos/$proyectoId'
      path: '/proyectos/$proyectoId'
      fullPath: '/proyectos/$proyectoId'
      preLoaderRoute: typeof ProyectosProyectoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes_/proveedores/canva/retorno': {
      id: '/ajustes_/proveedores/canva/retorno'
      path: '/canva/retorno'
      fullPath: '/ajustes/proveedores/canva/retorno'
      preLoaderRoute: typeof AjustesProveedoresCanvaRetornoRouteImport
      parentRoute: typeof AjustesProveedoresRoute
    }
  }
}

interface AjustesProveedoresRouteChildren {
  AjustesProveedoresCanvaRetornoRoute: typeof AjustesProveedoresCanvaRetornoRoute
}

const AjustesProveedoresRouteChildren: AjustesProveedoresRouteChildren = {
  AjustesProveedoresCanvaRetornoRoute: AjustesProveedoresCanvaRetornoRoute,
}

const AjustesProveedoresRouteWithChildren =
  AjustesProveedoresRoute._addFileChildren(AjustesProveedoresRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentesRoute: AgentesRoute,
  AjustesRoute: AjustesRoute,
  AprobacionesRoute: AprobacionesRoute,
  BandejaRoute: BandejaRoute,
  CalidadRoute: CalidadRoute,
  ColaRoute: ColaRoute,
  CompilacionesRoute: CompilacionesRoute,
  CopiasRoute: CopiasRoute,
  DocumentacionRoute: DocumentacionRoute,
  DominiosRoute: DominiosRoute,
  EstadoRoute: EstadoRoute,
  ExpertosRoute: ExpertosRoute,
  GastoIaRoute: GastoIaRoute,
  HabilidadesRoute: HabilidadesRoute,
  IntegracionesRoute: IntegracionesRoute,
  MesaRoute: MesaRoute,
  NuevaOrdenRoute: NuevaOrdenRoute,
  ReferenciaRoute: ReferenciaRoute,
  RepositoriosRoute: RepositoriosRoute,
  ResumenesRoute: ResumenesRoute,
  VigilanciaRoute: VigilanciaRoute,
  VozRoute: VozRoute,
  AjustesProveedoresRoute: AjustesProveedoresRouteWithChildren,
  ProyectosProyectoIdRoute: ProyectosProyectoIdRoute,
  ProyectosIndexRoute: ProyectosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
