/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentesRouteImport } from './routes/agentes'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as AprobacionesRouteImport } from './routes/aprobaciones'
import { Route as ColaRouteImport } from './routes/cola'
import { Route as EstadoRouteImport } from './routes/estado'
import { Route as IntegracionesRouteImport } from './routes/integraciones'
import { Route as NuevaOrdenRouteImport } from './routes/nueva-orden'
import { Route as ReferenciaRouteImport } from './routes/referencia'
import { Route as AjustesProveedoresRouteImport } from './routes/ajustes_.proveedores'
import { Route as ProyectosIndexRouteImport } from './routes/proyectos/index'
import { Route as ProyectosProyectoIdRouteImport } from './routes/proyectos/$proyectoId'
import { Route as AjustesProveedoresCanvaRetornoRouteImport } from './routes/ajustes_.proveedores.canva.retorno'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentesRoute = AgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const AprobacionesRoute = AprobacionesRouteImport.update({
  id: '/aprobaciones',
  path: '/aprobaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaRoute = ColaRouteImport.update({
  id: '/cola',
  path: '/cola',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadoRoute = EstadoRouteImport.update({
  id: '/estado',
  path: '/estado',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracionesRoute = IntegracionesRouteImport.update({
  id: '/integraciones',
  path: '/integraciones',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaOrdenRoute = NuevaOrdenRouteImport.update({
  id: '/nueva-orden',
  path: '/nueva-orden',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenciaRoute = ReferenciaRouteImport.update({
  id: '/referencia',
  path: '/referencia',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesProveedoresRoute = AjustesProveedoresRouteImport.update({
  id: '/ajustes_/proveedores',
  path: '/ajustes/proveedores',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosIndexRoute = ProyectosIndexRouteImport.update({
  id: '/proyectos/',
  path: '/proyectos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosProyectoIdRoute = ProyectosProyectoIdRouteImport.update({
  id: '/proyectos/$proyectoId',
  path: '/proyectos/$proyectoId',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesProveedoresCanvaRetornoRoute =
  AjustesProveedoresCanvaRetornoRouteImport.update({
    id: '/canva/retorno',
    path: '/canva/retorno',
    getParentRoute: () => AjustesProveedoresRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/ajustes': typeof AjustesRoute
  '/aprobaciones': typeof AprobacionesRoute
  '/cola': typeof ColaRoute
  '/estado': typeof EstadoRoute
  '/integraciones': typeof IntegracionesRoute
  '/nueva-orden': typeof NuevaOrdenRoute
  '/referencia': typeof ReferenciaRoute
  '/ajustes/proveedores': typeof AjustesProveedoresRouteWithChildren
  '/proyectos/$proyectoId': typeof ProyectosProyectoIdRoute
  '/proyectos/': typeof ProyectosIndexRoute
  '/ajustes/proveedores/canva/retorno': typeof AjustesProveedoresCanvaRetornoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/ajustes': typeof AjustesRoute
  '/aprobaciones': typeof AprobacionesRoute
  '/cola': typeof ColaRoute
  '/estado': typeof EstadoRoute
  '/integraciones': typeof IntegracionesRoute
  '/nueva-orden': typeof NuevaOrdenRoute
  '/referencia': typeof ReferenciaRoute
  '/ajustes/proveedores': typeof AjustesProveedoresRouteWithChildren
  '/proyectos/$proyectoId': typeof ProyectosProyectoIdRoute
  '/proyectos': typeof ProyectosIndexRoute
  '/ajustes/proveedores/canva/retorno': typeof AjustesProveedoresCanvaRetornoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/ajustes': typeof AjustesRoute
  '/aprobaciones': typeof AprobacionesRoute
  '/cola': typeof ColaRoute
  '/estado': typeof EstadoRoute
  '/integraciones': typeof IntegracionesRoute
  '/nueva-orden': typeof NuevaOrdenRoute
  '/referencia': typeof ReferenciaRoute
  '/ajustes_/proveedores': typeof AjustesProveedoresRouteWithChildren
  '/proyectos/$proyectoId': typeof ProyectosProyectoIdRoute
  '/proyectos/': typeof ProyectosIndexRoute
  '/ajustes_/proveedores/canva/retorno': typeof AjustesProveedoresCanvaRetornoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agentes'
    | '/ajustes'
    | '/aprobaciones'
    | '/cola'
    | '/estado'
    | '/integraciones'
    | '/nueva-orden'
    | '/referencia'
    | '/ajustes/proveedores'
    | '/proyectos/$proyectoId'
    | '/proyectos/'
    | '/ajustes/proveedores/canva/retorno'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agentes'
    | '/ajustes'
    | '/aprobaciones'
    | '/cola'
    | '/estado'
    | '/integraciones'
    | '/nueva-orden'
    | '/referencia'
    | '/ajustes/proveedores'
    | '/proyectos/$proyectoId'
    | '/proyectos'
    | '/ajustes/proveedores/canva/retorno'
  id:
    | '__root__'
    | '/'
    | '/agentes'
    | '/ajustes'
    | '/aprobaciones'
    | '/cola'
    | '/estado'
    | '/integraciones'
    | '/nueva-orden'
    | '/referencia'
    | '/ajustes_/proveedores'
    | '/proyectos/$proyectoId'
    | '/proyectos/'
    | '/ajustes_/proveedores/canva/retorno'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentesRoute: typeof AgentesRoute
  AjustesRoute: typeof AjustesRoute
  AprobacionesRoute: typeof AprobacionesRoute
  ColaRoute: typeof ColaRoute
  EstadoRoute: typeof EstadoRoute
  IntegracionesRoute: typeof IntegracionesRoute
  NuevaOrdenRoute: typeof NuevaOrdenRoute
  ReferenciaRoute: typeof ReferenciaRoute
  AjustesProveedoresRoute: typeof AjustesProveedoresRouteWithChildren
  ProyectosProyectoIdRoute: typeof ProyectosProyectoIdRoute
  ProyectosIndexRoute: typeof ProyectosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentes': {
      id: '/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AgentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprobaciones': {
      id: '/aprobaciones'
      path: '/aprobaciones'
      fullPath: '/aprobaciones'
      preLoaderRoute: typeof AprobacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cola': {
      id: '/cola'
      path: '/cola'
      fullPath: '/cola'
      preLoaderRoute: typeof ColaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estado': {
      id: '/estado'
      path: '/estado'
      fullPath: '/estado'
      preLoaderRoute: typeof EstadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integraciones': {
      id: '/integraciones'
      path: '/integraciones'
      fullPath: '/integraciones'
      preLoaderRoute: typeof IntegracionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-orden': {
      id: '/nueva-orden'
      path: '/nueva-orden'
      fullPath: '/nueva-orden'
      preLoaderRoute: typeof NuevaOrdenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referencia': {
      id: '/referencia'
      path: '/referencia'
      fullPath: '/referencia'
      preLoaderRoute: typeof ReferenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes_/proveedores': {
      id: '/ajustes_/proveedores'
      path: '/ajustes/proveedores'
      fullPath: '/ajustes/proveedores'
      preLoaderRoute: typeof AjustesProveedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/': {
      id: '/proyectos/'
      path: '/proyectos'
      fullPath: '/proyectos/'
      preLoaderRoute: typeof ProyectosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/$proyectoId': {
      id: '/proyectos/$proyectoId'
      path: '/proyectos/$proyectoId'
      fullPath: '/proyectos/$proyectoId'
      preLoaderRoute: typeof ProyectosProyectoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes_/proveedores/canva/retorno': {
      id: '/ajustes_/proveedores/canva/retorno'
      path: '/canva/retorno'
      fullPath: '/ajustes/proveedores/canva/retorno'
      preLoaderRoute: typeof AjustesProveedoresCanvaRetornoRouteImport
      parentRoute: typeof AjustesProveedoresRoute
    }
  }
}

interface AjustesProveedoresRouteChildren {
  AjustesProveedoresCanvaRetornoRoute: typeof AjustesProveedoresCanvaRetornoRoute
}

const AjustesProveedoresRouteChildren: AjustesProveedoresRouteChildren = {
  AjustesProveedoresCanvaRetornoRoute: AjustesProveedoresCanvaRetornoRoute,
}

const AjustesProveedoresRouteWithChildren =
  AjustesProveedoresRoute._addFileChildren(AjustesProveedoresRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentesRoute: AgentesRoute,
  AjustesRoute: AjustesRoute,
  AprobacionesRoute: AprobacionesRoute,
  ColaRoute: ColaRoute,
  EstadoRoute: EstadoRoute,
  IntegracionesRoute: IntegracionesRoute,
  NuevaOrdenRoute: NuevaOrdenRoute,
  ReferenciaRoute: ReferenciaRoute,
  AjustesProveedoresRoute: AjustesProveedoresRouteWithChildren,
  ProyectosProyectoIdRoute: ProyectosProyectoIdRoute,
  ProyectosIndexRoute: ProyectosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
