// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


// Proyecto propio de Supabase: valores fijados como respaldo (la clave publicable no es secreta).
const SUPABASE_PROJECT_ID_RESPALDO = 'eqyuodrmlbclobaverdb';
const SUPABASE_URL_RESPALDO = 'https://eqyuodrmlbclobaverdb.supabase.co';
const SUPABASE_PUBLISHABLE_KEY_RESPALDO = 'sb_publishable_tQgS3KEHYJC1jOx4XQCH6w_VL44Avu_';

// Proyecto antiguo ya retirado: cualquier variable que apunte a él se ignora.
const PROYECTO_RETIRADO = 'pfmgjoxddrebwneprldl';

function valorPropio(valor: string | undefined): string | undefined {
  if (!valor || valor.trim() === '') return undefined;
  if (valor.includes(PROYECTO_RETIRADO)) return undefined;
  return valor;
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  // Si la variable está vacía o apunta al proyecto retirado, se usa siempre el proyecto propio.
  const SUPABASE_URL =
    valorPropio(import.meta.env['VITE_SUPABASE_URL']) ||
    valorPropio(process.env['SUPABASE_URL']) ||
    SUPABASE_URL_RESPALDO;
  const SUPABASE_PUBLISHABLE_KEY =
    valorPropio(import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY']) ||
    valorPropio(process.env['SUPABASE_PUBLISHABLE_KEY']) ||
    SUPABASE_PUBLISHABLE_KEY_RESPALDO;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Faltan variables de Supabase: ${missing.join(', ')}.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  void SUPABASE_PROJECT_ID_RESPALDO;

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

